# Generated by Django 6.1.1 on 2026-09-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
