# Generated by Django 6.1.1 on 2026-09-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_todo_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="important",
            field=models.BooleanField(default=False),
        ),
    ]
