# Generated by Django 6.1.1 on 2026-09-08 08:22

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_todo_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="start_date",
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
